### ISSUE TITLE
Undefined reference to fake_stdin, stdout, and stderr

### ISSUE THREAD

**Issue by mbates14** [haarer/toolchain68k#1]
So playing around with this, When compiling the m68k_example, I get the following:

appinit.c:26: undefined reference to `__sf_fake_stdin'

Not entirely sure what the cause of this is. I assume something with newlib, but not sure where to look. 

any ideas?

**Comment by haarer** [comment]
The newlib build was broken, i added this patch to fix it. 
https://patches-gcc.linaro.org/patch/10140/
I got a totally different error message when i tested it, though.

**Comment by mbates14** [comment]
I ended up figuring out how to make it work in some miracle fashon. it kept dumping errors during compilation and compilation was very slow for some reason. 

So I took the reent flag from this build script, and put it into another build script, and now I can get the example to compile, although I have not tested yet (Still working on finishing the hardware). 

Here is the script I used: (Adding the reent flag)

http://www.aaldert.com/outrun/gcc.html

**Comment by haarer** [comment]
Are you working on developing Software for the outrun board?

Have you considered the platformio Environment ? Together with vscode it is an excellent development Environment .

Am 30. Oktober 2019 12:52:18 MEZ schrieb mbates14 <notifications@github.com>:
>I ended up figuring out how to make it work in some miracle fashon. it
>kept dumping errors during compilation and compilation was very slow
>for some reason. 
>
>So I took the reent flag from this build script, and put it into
>another build script, and now I can get the example to compile,
>although I have not tested yet (Still working on finishing the
>hardware). 
>
>Here is the script I used: (Adding the reent flag)
>
>http://www.aaldert.com/outrun/gcc.html
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/haarer/toolchain68k/issues/1#issuecomment-547864957

-- 
Gruß,
Alexander

**Comment by mbates14** [comment]
No I am developing software for a custom MC68010 device that I had reverse engineered. (it was a proprietary graphics system that is undocumented anywhere). 

I was playing with both toolchains, and then I tried yet another one elsewhere. 

I really do not know what I am doing on the C side of things (I know Arduino C stuff, thats it). I am a hardware engineer and just getting into software.
